emTrTable/urls.py
from django.conf.urls import url, include
from emTrTable.views import *
from . import views as core_views
from django.contrib.auth import login
from rest_framework.decorators import action
from rest_framework import routers, views
from emTrTable.views import EmployeeViewSet



router = routers.DefaultRouter()
router.register(r'EmployeeViewSet', EmployeeViewSet, basename='EmployeeView')

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^$', index),
    url(r'^jsonTableAll', getjsonTable),
    url(r'^jsonTableByID', getTableByBossId),
    url(r'^searchBy', serchby),
    url(r'^detailPage', detailPage),
    url(r'^api/', include(router.urls)),
]

employeeTree/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^auth/', include('django.contrib.auth.urls')),
    url('', include('emTrTable.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emTrTable/models.py
from django.db import models

# Create your models here.

class EmployeeTreeModel(models.Model):
    fullName = models.CharField(max_length=200)
    position = models.CharField(max_length=30)
    salary = models.IntegerField()
    employeeDate = models.DateField()
    bossID = models.IntegerField()
    level = models.IntegerField()
    photo = models.ImageField(upload_to='img',blank=True,null=True)
    bossName = models.CharField(max_length=200)

    def __str__(self):
        return self.fullName

emTrTable/views.py
from django.shortcuts import render, redirect
from .models import EmployeeTreeModel
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.http import JsonResponse
from rest_framework import viewsets
from emTrTable.mySerializers import EmployeeSerializer
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication, BasicAuthentication






class EmployeeForm(forms.ModelForm):
    use_required_attribute = True
    photo = forms.ImageField(required=False)
    class Meta:
        model = EmployeeTreeModel
        fields = ['fullName', 'position', 'photo', 'salary', 'employeeDate', 'bossID', 'level', 'id','bossName']

class EmployeeViewSet(viewsets.ModelViewSet):
    authentication_classes = (SessionAuthentication, BasicAuthentication)
    queryset = EmployeeTreeModel.objects.all()
    serializer_class = EmployeeSerializer
    permission_classes = [IsAuthenticated]


    @action(detail=False)
    def searchByfield(self, request):
        options = dict(request.GET)
        for opt in options:
            options[opt] = options[opt][0]
        filtered = self.queryset.filter(**options)
        serialized = self.serializer_class(filtered, many=True)
        return Response(serialized.data)

def index(request):
    if request.user.is_authenticated:
        return render(request, 'emploeeTreeTable.html')
    else:
        return redirect('auth/login')

def getjsonTable(request):
    if request.user.is_authenticated:
        employees = EmployeeTreeModel.objects.all().filter(level__lte=4).order_by('fullName')
        response_data = EmployeeSerializer(employees, many=True).data

        return JsonResponse({'table':response_data}, safe=True)
    else:
        return redirect('auth/login')

def getTableByBossId(request):
    if request.user.is_authenticated:
        bossID = request.GET.get('bossID')
        order_by = request.GET.get('order_by') if request.GET.get('order_by') != '' else 'fullName'
        employees = EmployeeTreeModel.objects.all().filter(bossID=bossID).order_by(order_by)
        response_data = EmployeeSerializer(employees, many=True).data
        return JsonResponse({'table':response_data})
    else:
        return redirect('auth/login')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            #user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

def logiView(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # Redirect to a success page.
        redirect('')


def serchby(request):
    if request.user.is_authenticated:
        options = dict(request.GET)
        for opt in options:
            options[opt] = options[opt][0]
        responded = EmployeeTreeModel.objects.filter(**options)
        serialized = EmployeeSerializer(responded, many=True)
        return JsonResponse({'table':serialized.data})
    else:
        return redirect('auth/login')

def detailPage(request):
    if request.user.is_authenticated:
        pageID = request.GET.get('ID')
        article = EmployeeTreeModel.objects.get(pk=pageID)
        if int(pageID) > 1:
            bosses = EmployeeTreeModel.objects.all().filter(level__lt=5)
        else:
            bosses = 'False'
        if request.method == 'POST':
            form = EmployeeForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                return redirect('/detailPage?ID='+str(article.id))
        else:


            form = EmployeeForm(instance=article)

            return render(request, 'detailPage.html', {'form': form, 'bossList':bosses})

emTrTable/templates/detailPage.html
{% extends 'Home.html' %}

{% block content %}
    {% load staticfiles %}

<div id="detailBlock" class="container">
<form name="editDetails" id="saveForm" method="post" enctype="multipart/form-data">

    <div class="leftBlock formBlock" >
        {% if form.photo.value %}
        <div id="imgBlock" align="left"><img width="{{ form.photo.width }}" height="{{ form.photo.height }}" src="{{ form.photo.value.url }}"/></div>

        {%  endif %}
  {{ form.photo }}

    </div>

    <div class="rightBlock formBlock" >

    <div class="form-group"><label>Position</label>{{ form.position }}</div>
    {% for error in form.position.errors %}
    <div class="form-group"> style="color: red">{{ error }}</div>
    {% endfor %}
        <div class="form-group"><label>Full name</label>{{ form.fullName }}</div>
    {% for error in form.fullName.errors %}
    <div class="form-group">{{ error }}</div>
    {% endfor %}
    <div class="form-group"><label>Employed start</label>{{ form.employeeDate }}</div>
    
    <div class="form-group"><label>Salary</label>{{ form.salary }}</div>
    <p style="display: none" id="bossID">{{ form.bossID }}</p>
    {% if bossList != 'False' %}
        <div class="form-group">
        <label>Boss</label>
    <select onchange="changeLevel(this);return false;">
    {% for boss in bossList %}
        {% if form.bossID.value == boss.id %}

        <option selected value="{{ boss.id }}" onclick="" id="{{ boss.id }}">{{ boss.fullName }}</option>
        {% else %}
             <option value="{{ boss.id }}" onclick="" id="{{ boss.id }}">{{ boss.fullName }}</option>
        {% endif %}
        {% endfor %}
    </select>
        </div>
    {% endif %}
    <p style="display: none;" id="inputlevel">{{ form.level }}</p>
    {% csrf_token %}
    <p id="bossNameContainer" style="display: none">{{ form.bossName }}</p>




        <p><button type="submit">Save changes</button></p>
    </div>
</form>

{% for boss in bossList %}
<input hidden value="{{ boss.level }}" id="id{{ boss.id }}">
{% endfor %}

<script>
   $("#ii").submit(function(e) {
    e.preventDefault();
    console.log(this);
    var formData = new FormData(this);

    console.log(formData['csrfmiddlewaretoken']);

    $.ajax({
        url: window.location.pathname,
        type: 'POST',
        beforeSend: function (xhr) {
        xhr.setRequestHeader("X-CSRFToken", formData['csrfmiddlewaretoken']);
        },
        data: formData,
        success: function (data) {
            alert(data)
        },
        cache: false,
        contentType: false,
        processData: false
    });
});
   function changeLevel(elemnt) {

       var bossId = elemnt.value;
       var level = parseInt($('#id'+bossId).val())+1;
       var bossNamevar = $('#'+bossId).html();
       console.log(bossNamevar);

       $("#id_level").remove();
       $("#inputlevel").append('<input type="number" name="level" value="'+level+'" required="" id="id_level">');
       $("#id_bossID").remove();
       $("#bossID").append('<input type="number" name="bossID" value="'+bossId+'" required="" id="id_bossID">');
       $('#id_bossName').remove();
       $('#bossNameContainer').append('<input type="text" name="bossName" value="'+bossNamevar+'" maxlength="200" required="" id="id_bossName">');

   }

</script>
</div>
{% endblock %}

emTrTable/templates/emploeeTreeTable.html
{% extends 'Home.html' %}

{% block content %}
        <div class="container">
            <span>
            <form name="searcher" class="form-inline" id="searchForm">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" id="searchInput" name="inputTerm" placeholder="Search area">
            </div>
            <div class="form-group">
                <select class="form-control search_selector" name="searchBy">
                        <option value="position__icontains">Position</option>
                        <option value="fullName__icontains">Full Name</option>
                        <option value="salary__lte">Salary less</option>
                        <option value="salary__gte">Salary more</option>
                        <option value="bossID" >Boss Name</option>
                        <option value="employeeDate__lte" >Date before</option>
                        <option value="employeeDate__gte" >Date after</option>

                    </select>
            </div>

            <div class="form-group">
                <button type="button" onclick="searchByForm()" class="btn btn-primary">Submit</button>
            </div>

        </form>
            </span>


    <div align="center" class="container center_div">
          <a href="#" onclick="treeTable('expandAll')">Expand all</a>
          <a href="#" onclick="treeTable('collapseAll')">Collapse all</a>


        </div>
<div class="table-responsive">
<table id="employeeTable" class="treetable table" >
<thead class="thead-bright">
          <tr>
              <th><span></span></th>
              <th class=""><a href="#" onclick="toggleClass('triangle-icon_1')"><span>Position</span><span id="by_position" class="sorter triangle-icon_1"></span></a></th>
              <th class=""><a href="#" onclick="toggleClass('triangle-icon_2')"><span>Full Name</span><span id="by_fullName" class="sorter triangle-icon_2"></span></a></th>
              <th class=""><a href="#" onclick="toggleClass('triangle-icon_3')"><span>Boss Name</span><span id="by_bossName" class="sorter triangle-icon_3"></span></a></th>
              <th class=""><a href="#" onclick="toggleClass('triangle-icon_4')"><span>Salary</span><span id="by_salary" class="sorter triangle-icon_4"></span></a></th>
              <th><a href="#" onclick="toggleClass('triangle-icon_5')"><span>Employee date</span><span id="by_employeeDate" class="sorter triangle-icon_5"></span></a></th>
              <th><span>Detail</span></th>

          </tr>
        </thead>
<tbody id="0">
</tbody>
</table>
</div>
    </div>
    <div id="loaderBox"><div class="loader"></div></div>

{% endblock %}

emTrTable/templates/home.html
<html lang="en">
<head>
    {% load staticfiles %}
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <link href="{% static '/bootstrap/dist/css/bootstrap.css'%}" rel="stylesheet" type="text/css" />
    <link href="{% static '/css/default.css' %}" rel="stylesheet" type="text/css" />
    <script src="{% static '/js/default.js' %}"></script>
    <script src="{% static "/bootstrap/dist/js/bootstrap.js" %}"></script>

    <meta charset="UTF-8">
    <title>Tree Table</title>
</head>
<body>
<div class="testTask" style="text-align: center;padding: 20px;">
    <span id="homelink"><a href="/">Home</a> </span><span><a href="auth/logout" >logout</a></span>
</div>

{% block content %}

{% endblock %}

</body>
</html>

emTrTable/templates/signup.html
{% extends 'home.html' %}

{% block content %}

    <div class="container center_div">
  <form class="form-signup" method="post">
      <h2>Sign up</h2>
    {% csrf_token %}
    {% for field in form %}

        {{ field.label_tag }}
        {{ field }}

        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
  </form>
    </div>
{% endblock %}